### ISSUE TITLE
Grunt installer doesn't work for me at all

### ISSUE THREAD

**Issue by honzasladek** [ViliamKopecky/Ristretto#3]
I tried to install Ristretto via the new grunt command. It downloads everything but I'm unable to set everything properly for it to work. Could you please just make it one-command-does-it-all installer? ;)

Otherwise it's awesome!

**Comment by ViliamKopecky** [comment]
It's easier to use [RistrettoExample](https://github.com/ViliamKopecky/RistrettoExample) as boilerplate for Ristertto projects.

**Comment by honzasladek** [comment]
Yeah, that's what I did. ;) But would be lovely to install it by one command instead of clonning the repo.
